name: CI publish

on:
  push:
    tags:
      - '*'

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6

  build:
    name: Build and publish
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21.0.2'

      - name: Run Gradle build
        run: ./gradlew publishPlugins -x test -PTAG_VERSION=${VERSION}
        env:
          VERSION: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyName: ${{ secrets.SIGNING_KEYNAME }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PLUGIN_PORTAL_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PLUGIN_PORTAL_SECRET }}
