name: CI publish

on:
  push:
    tags:
      - '*'

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

  build:
    name: Build and publish
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21.0.2'

      - name: Configure GPG
        run: |
          cat <<EOT >> ./gpgkey
          ${{ secrets.SIGNING_KEY }}
          EOT
          gpg --batch --import ./gpgkey
          gpg --pinentry-mode=loopback --passphrase ${{ secrets.SIGNING_PASSWORD }} --export-secret-keys > ~/.gnupg/secring.gpg

      - name: Set up Gradle properties
        run: |
          cat <<EOT >> ./gradle.properties
          signing.keyId=${{ secrets.SIGNING_KEYNAME }}
          signing.password=${{ secrets.SIGNING_PASSWORD }}
          signing.secretKeyRingFile=$HOME/.gnupg/secring.gpg
          EOT

      - name: Run Gradle build
        run: ./gradlew publishPlugins -x test -PTAG_VERSION=${VERSION} -Pgradle.publish.key=${PLUGIN_KEY} -Pgradle.publish.secret=${PLUGIN_SECRET}
        env:
          VERSION: ${{ github.ref_name }}
          PLUGIN_KEY: ${{ secrets.GRADLE_PLUGIN_PORTAL_KEY }}
          PLUGIN_SECRET: ${{ secrets.GRADLE_PLUGIN_PORTAL_SECRET }}
